trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  serverName: 'sqlserverbacpac.database.windows.net'
  sourceDatabaseName: 'DB-POS-original'
  importedDatabaseName: 'DB-POS-updated' 
  username: 'bacpacuser'
  password: 'bacpac@12'
  bacpacFilePath: '$(Agent.TempDirectory)/exported.bacpac'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet tool install -g microsoft.sqlpackage
  displayName: 'Install SqlPackage'

- script: |
    sqlpackage /Action:Export ^
      /ssn:$(serverName) ^
      /sdn:$(sourceDatabaseName) ^
      /su:$(username) ^
      /sp:$(password) ^
      /tf:"$(bacpacFilePath)"
  displayName: 'Export .bacpac from Source DB'

- script: |
    sqlpackage /Action:Import ^
      /sf:"$(bacpacFilePath)" ^
      /tsn:$(serverName) ^
      /tdn:$(importedDatabaseName) ^
      /tu:$(username) ^
      /tp:$(password)
  displayName: 'Import .bacpac into New DB'

# - script: |
#     sqlcmd -S $(serverName) -d $(importedDatabaseName) -U $(username) -P $(password) ^
#       -Q "CREATE TABLE ExtraTable (Id INT PRIMARY KEY, Note NVARCHAR(255))"
#   displayName: 'Add Table to Imported DB'
